#!/bin/bash

# Description: Tell the color of a fruit

# Confirm 1 argument is provided
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <fruit>" >&2
    exit 2
fi

# force lowercase to catch all possible variations of fruit name 
fruit="${1,,}"

# accepted fruit are {apple:banana:kiwi:orange:grape}
case "$fruit" in
    apple)
        echo "Apples are red, yellow or green"
        ;;
    banana)
        echo "Bananas are yellow"
        ;;
    kiwi)
	    echo "Kiwifruit are gold, green or red"
	    ;;
    orange)
        echo "Oranges are orange"
        ;;
    grape)
        echo "Grapes are purple or green"
        ;;
    *)
        echo "Unknown fruit: $fruit" >&2
       	echo "Choose: apple, banana, kiwi, orange or grape"
        exit 1
        ;;
esac
